statics_url: https://adelnor.com/statics/
development: false
debug: false
cors:
  active: false
  domains:
    - www.adelnor.com
    - adelnor.com
timezone: America/Mazatlan
auth:
  hash: VQ!R8?(GV*pAM)vKe^WvxC!$pB681d8u
mailer:
  host: secure.emailsrvr.com
  user: mailer@adelnor.com
  password: R00ster+=21
  email: mailer@adelnor.com
  port: 465
  smtp_secure: ssl
  smtp_auth: true
  debug: 0
  smtp: true
  sender: Adelnor
recipients:
   contact:
     email: dev@chavodigital.com
     name: Contacto
   jobs:
     email: dev@chavodigital.com
     name: Bolsa de trabajo
