statics_url: https://adelnor.com/statics/
development: false
debug: false
cors:
  active: false
  domains:
    - www.adelnor.com
    - adelnor.com
timezone: America/Mazatlan
auth:
  hash: VQ!R8?(GV*pAM)vKe^WvxC!$pB681d8u
mailer:
  host: mail.roomyhost.com
  user: dev@chavodigital.com
  password: FlH^9XC$5WW!19KC
  email: dev@chavodigital.com
  port: 465
  smtp_secure: ssl
  smtp_auth: true
  debug: 0
  smtp: true
  sender: Adelnor
recipients:
   contact:
     email: jramirez@adelnor.com
     name: Contacto
   jobs:
     email: rpadilla@adelnor.com
     name: Bolsa de trabajo
