statics_url: https://apimailer.cris.com.mx/statics/
development: true
debug: true
cors:
  active: true
  domains: null
timezone: America/Mazatlan
auth:
  uuid: 92eb5920-a627-4cde-8428-485d0229ef87
  hash: VQ!R8?(GV*pAM)vKe^WvxC!$pB681d8u
mailer:
  host: mail.roomyhost.com
  user: dev@chavodigital.com
  password: FlH^9XC$5WW!19KC
  email: dev@chavodigital.com
  port: 465
  smtp_secure: ssl
  smtp_auth: true
  debug: 0
  smtp: true
  sender: Chavo Digital
recipients:
   contact:
     to:
       email: dev@chavodigital.com
       name: Contacto
     cc:
       email: cristian@migarage.mx
       name: Chavo Digital
   jobs:
     to:
       email: dev@chavodigital.com
       name: Bolsa de trabajo
     cc:
       email: cristian@migarage.mx
       name: Chavo Digital
mailchimp:
  key: 02971832e08effec5afd4fc402fffe25-us20
  server: us20
  client_id: 372741327071
  list_id: f907d7c9f2

